language: node_js
node_js:
- 8.9.1
sudo: false
cache:
  directories:
    - node_modules
    - themes/tranquilpeak/node_modules
before_install:
- npm install hexo-cli -g
install:
- npm install
branches:
  only:
  - source
before_script:
- git config --global user.name 'anbuchelva'
- git config --global user.email 'anbuchelva@gmail.com'
- sed -i'' "s~git@github.com:anbuchelva/anbuchelva.github.io.git~https://${GH_TOKEN}:x-oauth-basic@github.com/anbuchelva/anbuchelva.github.io.git~"
  _config.yml
script:
- cp -rf themes/customize_tranquilpeak/* themes/tranquilpeak
- cd themes/tranquilpeak
- npm install
- npm install grunt-cli -g
- npm install bower -g
- bower install
- grunt buildProd
- cd ..
- hexo clean
- hexo algolia
- hexo deploy
